### ISSUE TITLE
Unclear about email ground truth ... please help

### ISSUE THREAD

**Issue by prithvirajsen** [Parth27/Lin#9]
I am trying to understand the ground truth in the email data.

If I look at Preprocessed_Dataset_email.xlsx, in row 32 I see the sentence:

- "Please hold open the first Monday of every quarter from 8:30 a.m. to 12:00 p.m. for this purpose."

For which the 'Verbs' column says 'open' is the 'Task'.

However, when I parse Datasets/email/tasks_email.pickle and Datasets/email/VP_df_email.pickle, I see this:

- ('Please hold open .', 'hold') 1
- ('open Monday a.m. p.m.', 'open') 0

The last 0/1 is the corresponding label from tasks_email.pickle. This would suggest that 'hold' and not 'open' is the 'Task' which is in contrast to what the xlsx file says.

Which is the correct ground truth? Also, which ground truth did you use for the results in your COLING 2020 paper?

regards
prithvi

**Comment by prithvirajsen** [comment]
@Parth27 could you please help with the above question?

**Comment by Parth27** [comment]
> I am trying to understand the ground truth in the email data.
> 
> If I look at Preprocessed_Dataset_email.xlsx, in row 32 I see the sentence:
> 
> * "Please hold open the first Monday of every quarter from 8:30 a.m. to 12:00 p.m. for this purpose."
> 
> For which the 'Verbs' column says 'open' is the 'Task'.
> 
> However, when I parse Datasets/email/tasks_email.pickle and Datasets/email/VP_df_email.pickle, I see this:
> 
> * ('Please hold open .', 'hold') 1
> * ('open Monday a.m. p.m.', 'open') 0
> 
> The last 0/1 is the corresponding label from tasks_email.pickle. This would suggest that 'hold' and not 'open' is the 'Task' which is in contrast to what the xlsx file says.
> 
> Which is the correct ground truth? Also, which ground truth did you use for the results in your COLING 2020 paper?
> 
> regards
> prithvi

The dataset was slightly modified later which and the pickle files are ones generated from the older version of dataset.
Please delete the pickle files in your local repo and rerun Lin, I will upload the updated pickle files soon.

**Comment by prithvirajsen** [comment]
Thanks for responding. I read your response as the xlsx file containing the ground truth (specifically: the verbs and tasks column).

In that case, I have another question regarding this line in the code: https://github.com/Parth27/Lin/blob/aaf0fe28ba28637d0bc92a4a5696131b191905e6/code/Semantics_module.py#L136

What is it doing specifically? Since Verbs in data is the ground truth, is it peeking while making predictions? Seems like it checks if the ground truth for the sentence has any verbs and if there aren't any then the code refrains from making any predictions (thus avoiding false positives). 

To confirm, I manually commented that 'if' stmt off so control flows to the else block directly and the resulting precision is much lower than what's reported in the paper. This would seem to confirm my observation. Any clarification about this issue would be much appreciated.

regards
prithvi

**Comment by Parth27** [comment]
Our annotated dataset has a lot of sentences which do not have tasks and Lin, being a simple heuristic approach, is unable to deal with them. Which is why, for evaluation purposes we are only sampling those sentences from the dataset which have tasks in them.

**Comment by prithvirajsen** [comment]
I see. Many thanks for the clarifications.
